# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FindShift_cpp <- function(rho, X, A, b) {
    .Call(`_LinConGauss_FindShift_cpp`, rho, X, A, b)
}

xtheta_cpp <- function(theta, x0, nu) {
    .Call(`_LinConGauss_xtheta_cpp`, theta, x0, nu)
}

LinESS_cpp <- function(A, b, N, x0, nskip) {
    .Call(`_LinConGauss_LinESS_cpp`, A, b, N, x0, nskip)
}

SubsetSim_cpp <- function(A, b, N, rho, nskip) {
    .Call(`_LinConGauss_SubsetSim_cpp`, A, b, N, rho, nskip)
}

HDR_algo_cpp <- function(A, b, gamma_vec, N, nskip) {
    .Call(`_LinConGauss_HDR_algo_cpp`, A, b, gamma_vec, N, nskip)
}

mcint_lincon <- function(N, A, b) {
    .Call(`_LinConGauss_mcint_lincon`, N, A, b)
}

